### ISSUE TITLE
Error while trying to run dfast -- Barrnap and time-piece related

### ISSUE THREAD

**Issue by matrs** [nigyta/dfast_core#10]
Hello,
 I used `DFAST` successfully in mac osx a few weeks ago. Now I'm trying to run it in `arch Linux` but I'm getting this error:

`$DFAST --genome "$PATH1/16572_RC-21.fsa" -o DFAST_16572_RC-21 --cpu 4 --force --debug`

```
2018/10/15 22:33:40 Running on Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)].
2018/10/15 22:33:40 Loading a config file from /run/media/mibu/BioNano1/dfast_core/dfc/default_config.py
2018/10/15 22:33:40  WARNING Debug mode enabled. Logger level is set to DEBUG and temporary files will be kept. [dfast 121]
2018/10/15 22:33:40     INFO OS type is Linux. [path_util 40]
2018/10/15 22:33:40     INFO Adding /run/media/mibu/BioNano1/dfast_core/bin/Linux to PATH. [path_util 42]
2018/10/15 22:33:40     INFO WORKING Directory is set to an existing directory: 'DFAST_16572_RC-21'. [path_util 19]
2018/10/15 22:33:40     INFO DFAST pipeline started. (version 1.0.8) [pipeline 38]
2018/10/15 22:33:40     INFO Results will be generated into 'DFAST_16572_RC-21'. [pipeline 39]
2018/10/15 22:33:40     INFO Loading a genomic fasta file from prokka_16572_RC-21/16572_RC-21.fsa [genome 36]
2018/10/15 22:33:40     INFO Genome source information: organism=, strain= [genome 60]
2018/10/15 22:33:40     INFO The query genome is treated as a draft genome with 182 sequences. [genome 109]
2018/10/15 22:33:40     INFO Sequences are sorted by length (from longer to shorter). [genome 112]
2018/10/15 22:33:40     INFO Sequences shorter than 200 will be eliminated. [genome 116]
2018/10/15 22:33:40     INFO Sequences will be renamed as sequence001, sequence002... [genome 127]
2018/10/15 22:33:40     INFO Locus_tag settings: locus_tag_prefix=LOCUS and step=10. [locus_tag_generator 18]
2018/10/15 22:33:40     INFO Locus_tags are assigned separately to each feature type. e.g. CDS: LOCUS_000xx, rRNA: LOCUS_r000xx, tRNA: LOCUS_t000xx, tmRNA: LOCUS_tm000xx. [locus_tag_generator 21]
2018/10/15 22:33:40     INFO Remove_Partial_Feature is enabled. [feature_util 25]
2018/10/15 22:33:40     INFO Remove_Overlapping_Feature is enabled. Priority: ['assembly_gap', 'CRISPR', ('tmRNA', 'tRNA', 'rRNA'), 'CDS'] [feature_util 29]
2018/10/15 22:33:40     INFO Initializing structural annotation tools...  [structuralAnnotation 48]
2018/10/15 22:33:40     INFO GAPannotator initialized. (Version 1.0) [gap 45]
2018/10/15 22:33:40     INFO Setting GAPannotator options. {'len_cutoff': 5, 'linkage_evidence': 'paired-ends', 'gap_type': 'within scaffold'} [base_tools 30]
2018/10/15 22:33:40     INFO Checking MetaGeneAnnotator...  [mga 37]
2018/10/15 22:33:40    DEBUG Running command "mga 2>&1" (MGA) [base_tools 67]
2018/10/15 22:33:40     INFO MetaGeneAnnotator initialized. (Version 2008/08/19) [mga 41]
2018/10/15 22:33:40     INFO Setting MetaGeneAnnotator options. {'cmd_options': '-s'} [base_tools 30]
2018/10/15 22:33:40     INFO Checking Aragorn version...  [base_tools 39]
2018/10/15 22:33:40    DEBUG Running command "aragorn -h" (Aragorn) [base_tools 67]
2018/10/15 22:33:40     INFO Aragorn initialized. (Version 1.2.38) [base_tools 49]
2018/10/15 22:33:40     INFO Setting Aragorn options. {'gcode': '-gcbact', 'cmd_options': '-l'} [base_tools 30]
2018/10/15 22:33:40     INFO Checking Barrnap version...  [base_tools 39]
2018/10/15 22:33:40    DEBUG Running command "barrnap --version 2>&1" (Barrnap) [base_tools 67]
2018/10/15 22:33:40    ERROR Barrnap version could not be determined. Aborted... [base_tools 51]
2018/10/15 22:33:40    ERROR This may happen if Time::Piece cannot be found. If you are using CentOS/RedHat, try 'sudo yum install perl-Time-Piece'. [base_tools 53]
```

It seems to me that all the required software is installed as you can see here (I'm using conda to manage packages):
```
conda list |grep -E 'barrnap|perl-time-piece'
barrnap                   0.9                           2    bioconda
perl-time-piece           1.27                    pl526_1    bioconda
```
Also, I can see this in my `conda` environment 
`/media/mibu/Storage_SSD/Miniconda3/envs/bioc/conda-meta/perl-time-piece-1.27-pl526_1.json`

So any help would be really appreciated.

Regards

**Comment by nigyta** [comment]
Dear matrs,

Thank you for using DFAST.

As I'm not familiar with ArchLinux, I'm not sure if this helps. Hopefully, it works!

I guess you have installed Barrnap (ver 0.9) by yourself.
However it is not called from DFAST, 
because DFAST automatically adds "$DFAST_APP_ROOT/bin/Linux" at the head of "PATH" at execution time, and there is a link to the Barrnap executable in it.

So replace the link ($DFAST_APP_ROOT/bin/Linux/barrnap), and create a new link that points to the one you installed.
Then, DFAST will call Barrnap (ver 0.9) instead of the one bundled in the DFAST software package.
Alternatively, if barrnap is already in your PATH, just removing the $DFAST_APP_ROOT/bin/Linux/barrnap may work.

If this didn't work, please let me know your perl environment, e.g. path to the perl executable, the PERL5LIB enviromental variable.

Yasuhiro

**Comment by matrs** [comment]
Hi Yasushiro, thank you for your help.

I solved the issue, it ended up being about a  broken `barrnap` executable. When I decompressed `dfast`, the `barrnap` executable was only a few bytes of size and it seems that my disk was the culprit. I decompressed it in other disk and everything worked as expected, so the `barrnap` executable created in my first disk was broken, that's why it didn't work.

Not related to my previous issue, but this could be useful for other `arch linux` users.  Dfast was failing because `blastp` was looking for `libidn-11` and it didn't find it. I had to install `libidn-133-compat` from the `AUR` repository  to make it work. Maybe you can mention that in your Readme although I know It's hard to keep up with all the requirements for all the platforms/ Linux distributions.

Thank you again for your prompt answer 

Cheers

**Comment by nigyta** [comment]
libidn-11 requirement is mentioned in README
