### ISSUE TITLE
16S and 23S are sometimes not reported

### ISSUE THREAD

**Issue by dgg32** [nigyta/dfast_core#11]
Hello.

I am using dfast for genome annotation and notice that dfast reports no rRNA for most of genomes. barrnap has been run separately and in debug mode, in both cases it found one 23S and one 16S. But in the dfast run, none of them is reported.

**Comment by nigyta** [comment]
Thank you for using DFAST.

Are you working on draft genomes obtained from short reads?

Bacterial genomes usually harbors multiple copies of rRNAs. Genome assembly from short reads often fails in reconstructing such repetitive regions, yielding collapsed or fragmented sequences.
As a result, many of the rRNAs are found only partially at the ends of contigs.

By default, DFAST cleans up partially annotated features, so they are not reported in the final result.
To suppress this behavior, disable `remove_partial_features` in the config file. See below.

	
    FEATURE_ADJUSTMENT = {
        "remove_partial_features": False,  # <---- SET THIS TO False (default: True)

        "remove_overlapping_features": True, 
        "feature_type_priority": ["assembly_gap", "CRISPR", ("tmRNA", "tRNA", "rRNA"), "CDS"],

        "merge_cds": False, 
        "tool_type_priority": {"MGA": 0, "Prodigal": 1},
    }

**Comment by dgg32** [comment]
Hi thank you for the quick reply. Yes, it is a miseq sequenced genome. 

And your suggested fix works. Now I get both the 23S and 16S. Thank you.

But they are apparently not "partial". The 16S is 1496 bases long and the 23S 2089 bases long. At least, it looks like the 16S represents very much the full length sequence. And barrnap doesn't say the 16S is partial either. So why dfast determines they are partial please?

**Comment by dgg32** [comment]
[Barrnap.txt](https://github.com/nigyta/dfast_core/files/2649460/Barrnap.txt)
Here it is
