### ISSUE TITLE
error while trying to run dfast -- rpsblast

### ISSUE THREAD

**Issue by jeagull** [nigyta/dfast_core#12]
Hi all, thanks for your help in advance.

I was trying to annotate human microbiome genome using dfast and I got the following errors:

Process aborted due to an error in CDDsearch.
[rpsblast] Failed s_BlastXMLAddIteration Q(0/1
BLAST failed to write output

Any suggestions on what to do? I don't know if this is a bug in the program or my fna file...

![スクリーンショット 2019-04-12 12 01 40](https://user-images.githubusercontent.com/13218402/56009464-c8265900-5d1a-11e9-82b9-f6924fecc310.png)
![スクリーンショット 2019-04-12 12 01 48](https://user-images.githubusercontent.com/13218402/56009468-cbb9e000-5d1a-11e9-8282-e77450d7a3fb.png)

Thanks again for your help
Best regards

**Comment by nigyta** [comment]
Thank you for your report. But sorry, I have no idea on this.
Is it possible to send the input file? I'll look into it.

If it's okay, please upload the file at the web version of DFAST, https://dfast.nig.ac.jp/dfc/ 
After submitting the job, let me know the job id by email to dfast@nig.ac.jp
As DFAST web version accepts a file upto 15Mbyte, you may need to truncate the file.

Thank you.

Yasuhiro

**Comment by jeagull** [comment]
Hey Yasuhiro,

Thanks for your reply.

I am more than happy to send you the input file, but the thing is I have 1460 files which I have congregated into a single "input_file", and I use that congregated file for the analysis via supercomputer in Tokyo Human Genome Center. (Does this make sense...?) When I do dfast analysis against a single fasta file it works out completely fine so if you have no reports of a similar issue, then I guess it could be the problem with the supercomputer..? 

I don't know if you are familiar with supercomputer but I will attach the job script anyways. I will also attach the log file that was created when I did analysis on a single file.

[application.log](https://github.com/nigyta/dfast_core/files/3078099/application.log)

[dfast.txt](https://github.com/nigyta/dfast_core/files/3078113/dfast.txt)

[input_files.txt](https://github.com/nigyta/dfast_core/files/3078117/input_files.txt)

Best Regards,
Ryohei

**Comment by nigyta** [comment]
Thank you for the detail.
I looked into the files, but they seem to have no problems.
As you have guessed, it might be a specific problem with your computer or a very large-sized input file.


It seems that you submitted an array job to run DFAST on each genome.
Did it work?
```
#$ -t 1-1460:1
#$ -tc 10

#setting
source ~/.bash_profile
files=(`cat input_files`) #input files
TASK_ID=`expr ${SGE_TASK_ID} - 1` 
```
I think it's better and more stable than running with a large single congregated file, although slow.

**Comment by jeagull** [comment]
Dear Yasuhiro,

Sorry I couldn't send a reply sooner. I thought it was a fault with supercomputer so I tried doing the analysis once more and for some reason it worked out all right. I have tried several other input files in the same manner and they all worked. Thank you for your help and sorry to have troubled you!

Ryohei
