### ISSUE TITLE
Mac OS X 10.14.4 complains that mga is not adapted

### ISSUE THREAD

**Issue by flandrs** [nigyta/dfast_core#13]
Hello everybody,

All is in the title: OS X 10.14.4 complains that mga is not adapted to the newest OS X (and will not be working in the future).

However, it is currently working smoothly.

This may becomes a problem (soon ?) with the next OS X.

Sincerely

**Comment by nigyta** [comment]
Yes, the same warning appears on my Mac (OS X 10.14.3), but it works without any problem for now.
As you pointed out, it may not work in the future MacOS version.

Fortunately, the developper of MGA is in the same institute as me. So I will ask him to update the binary for MacOS.
Another option is to use Prodigal as a default gene prediction tool.

**Comment by flandrs** [comment]
Thank you for the reply

Yes Prodigal is certainly a pertinent alternative solution as it is very good performing

JPF
------------------------------------
Pr. emer.  JP Flandrois MD, PhD
Univ  Lyon. LBBE Laboratoire de Biometrie et Biologie Evolutive - http://lbbe.univ-lyon1.fr/
Team/ Equipe Bioinformatique, Phylogénie et Génomique Evolutive<http://lbbe.univ-lyon1.fr/-Equipe-Bioinformatique-Phylogenie-.html>
-------------------------------------
jean-pierre.flandrois@univ-lyon1.fr<http://univ-lyon1.fr/>
UMR 5558-LBBE. 43, Bd du 11 novembre 1918, Bâtiment Mendel 69622 Villeurbanne Cedex FRANCE
(Univ  Lyon, Université Lyon 1, CNRS, UMR 5558 , "Laboratoire de Biometrie et Biologie Evolutive" LBBE)
-----------------------------------
- Mobile/Cellular (only) : 33 6 63 22 55 00
- https://umr5558-bibiserv.univlyon1.fr/flandrois/index.html
--------------------------------------

On 17 Apr 2019, at 10:47, Yasuhiro Tanizawa <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, the same warning appears on my Mac (OS X 10.14.3), but it works without any problem for now.
As you pointed out, it may not work in the future MacOS version.

Fortunately, the developper of MGA is in the same institute as me. So I will ask him to update the binary for MacOS.
Another option is to use Prodigal as a default gene prediction tool.
