### ISSUE TITLE
Error running dfast -- Barrnap and Time::Piece

### ISSUE THREAD

**Issue by yyan823** [nigyta/dfast_core#14]
Hello,

I just installed dfast on Mac High Sierra, try to run it and get this error below:

`
> 2019/04/19 10:20:40 Checking Barrnap version... 
> 2019/04/19 10:20:40 Barrnap version could not be determined. Aborted...
> 2019/04/19 10:20:40 This may happen if Time::Piece cannot be found. If you are using CentOS/RedHat, try 'sudo yum install perl-Time-Piece'.

`

I tried to install cpanm and from cpanm install Time::Piece, but it didn't solve the problem. And I checked the dfast tools folder, everything seems unzipped ok (which was mentioned in previous similar issue). Could you please help to see how to solve this?

----------------
updates:

Replacing barrnap file in bin/Darwin with the one in bin/Darwin/barrnap-0.8/bin/ solved this.

Thank you so much!
Sincerely

**Comment by nigyta** [comment]
Dear yyan823,

Thank you for trying DFAST.
It's great to hear that. Feel free to ask again if you have any trouble.

Yasuhiro
