### ISSUE TITLE
Bioconda package?

### ISSUE THREAD

**Issue by tseemann** [nigyta/dfast_core#16]
The standard way to install bioinformatics packages and their dependencies is now Bioconda.

Do you have plans to write a bioconda recipe for DFAST?

**Comment by nigyta** [comment]
Dear Torsten,

Thank you for the suggestion.
I just added the recipe last week, and DFAST is now available from bioconda.
https://bioconda.github.io/recipes/dfast/README.html
When installed from bioconda, reference libraries will be automatically downloaded and indexed after installing dependencies and binaries. So it may take time.

ps
DFAST is greatly inspired from Prokka. Indeed, the original version of DFAST (web version) was based on Prokka, upon which the feature to create data submission files to DDBJ was integrated. Thank you for creating the wonderful tool!

Yasuhiro

**Comment by tseemann** [comment]
Thanks for the kind words, and for the update @nigyta  :)
