### ISSUE TITLE
Issues with trnascan-se after no-internet install

### ISSUE THREAD

**Issue by standage** [nigyta/dfast_core#21]
In https://github.com/bioconda/bioconda-recipes/issues/17982 I described my setup: my system has no internet connection, but we do have a local mirror of conda and bioconda. As of DFAST version 1.2.4, I can now successfully install DFAST without an internet connection. The first time I run it, DFAST detects that the databases have not yet been indexed and indexes them automatically.

I'm now attempting to run DFAST with trnascan-se instead of the default Aragorn. I'm getting the error:

```
2019/12/02 xx:xx:xx Start structural annotation process using 1 CPUs
2019/12/02 xx:xx:xx Process aborted due to an error in tRNAscan.
2019/12/02 xx:xx:xx /bin/sh: 1: Syntax error: Bad fd number
```

Is this related to installing DFAST with no internet connection?

**Comment by nigyta** [comment]
Please type:
```
$ tRNAscan-SE 
```
to check if it is found in your `PATH`.

If not, please install it:
```
conda install -c bioconda trnascan-se
```
DFAST can use tRNAscan, but it's not included in the software package. You need to install it separately.

Similarly, if you want to use Prodigal for searching coding genes, please install it with `conda install -c bioconda prodigal` and invoke dfast with `--use_prodigal` option.

**Comment by standage** [comment]
The binary is indeed in my path, version 2.0.3. Further up in the terminal the following messages are shown, long before DFAST attempts to run tRNAscan-SE.

```
2019/12/02 xx:xx:xx Checking tRNAscan-SE version...
2019/12/02 xx:xx:xx tRNAscan-SE initiallized. (Version 2.0.3)
2019/12/02 xx:xx:xx Setting tRNAscan-SE options. {'model': '-B', 'cmd_options': ''}
```

DFAST would presumably have failed at that stage if tRNAscan-SE couldn't be found in `$PATH`.

**Comment by nigyta** [comment]
Yes, tRNAscan seems to be properly installed.

I ran DFAST (1.2.4) with tRNAscan (2.0.3) installed from Bioconda, but I couldn't reproduce the error.

Could you run DFAST again with `--debug` option to show the command calling tRNAscan (like below)?
```
tRNAscan-SE -B  --brief --forceow --thread 1 --output OUT/structural/tRNAscan.txt OUT/input/genome.fna  >& OUT/structural/tRNAscan.log
```
The result and log are generated into OUT/structural/tRNAscan.txt and OUT/structural/tRNAscan.log
Could you paste them here or send them to me at dfast@nig.ac.jp ?

Also, is it possible to upload the genome to the web version (https://dfast.nig.ac.jp/dfc/)?
Please enable tRNAscan from the "Advanced Options".
If the error is reproduced, I will look into it.

**Comment by standage** [comment]
After a bit more investigation, it looks like the log redirection token is the culprit. The `>&` syntax is csh-specific, and not supported in sh and bash—see https://unix.stackexchange.com/q/407798/7415. The equivalent syntax supported in sh/bash is `2>&1`. After editing the offending file, DFAST runs fine.

**Comment by nigyta** [comment]
thank you for the PR
