### ISSUE TITLE
databases: specify location

### ISSUE THREAD

**Issue by nick-youngblut** [nigyta/dfast_core#30]
If dfast is installed via conda, then `dfast_file_downloader.py` will download all of the databases into the conda env. Conda was not meant to store large data files. Also, the databases must be re-downloaded each time the user creates a database that includes dfast, which can happen often if using snakemake or other pipeline software. It would be helpful to give the user the option to specify where the databases are downloaded to.

**Comment by nigyta** [comment]
Thank you for good suggestion!
Actually, I have similar problem while using a pipeline using CWL.
I'm going to add the option in the next update.

**Comment by nigyta** [comment]
In ver1.2.7, I have added an option `--dbroot` to specify the location of reference databases.
You can do so by specifying DFAST_DB_ROOT environmental option too.

I haven't changed Bioconda recipe yet. Please wait a little more until I update it.
