### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by blsteven** [nigyta/dfast_core#32]
I am getting the following error when I try to run the program

ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by nigyta** [comment]
Thank you for letting me know.
Actually, I’ve just got the same error after updating the Biopython to the latest version.
I’m going to fix this as soon as possible, but for now downgrading Biopython may fix this issue.

**Comment by blsteven** [comment]
Thanks for the quick response and the great tool!



Blaire Steven
Associate Scientist
Environmental Sciences
Connecticut Agricultural Experiment Station
203-974-8461
blaire.steven@ct.gov

Adjunct Assistant Research Professor
University of Connecticut
Dept. Natural Resources and the Environment


******************************************
This information may be confidential and/or privileged.
 If you received this in error, please inform the sender and remove any record of this message.
Note that messages to or from the State of Connecticut domain may be subject to Freedom of Information statutes and regulations.
*******************************************

________________________________

**Comment by nigyta** [comment]
@blsteven 

As of version 1.2.9, II have fixed this issue following the workaround shown here https://biopython.org/wiki/Alphabet
Confirmed that it works on both Biopython 1.71 and 1.78
Thanks again for letting me know.
