### ISSUE TITLE
[[enhancement]] add post-link.sh to conda

### ISSUE THREAD

**Issue by laxeye** [nigyta/dfast_core#38]
Dear developers, @nigyta,

is it possible to add post-link.sh file to bioconda recipe folder to automatically download default databases like in Dockerfile (commented line)? Otherwise after installation from conda user shouldn't forget to download the databases before running DFAST.

This file could include just two lines of code:

```
#!/bin/bash
dfast_file_downloader.py --protein dfast --cdd Cog --hmm TIGR
```

Regards,
Aleksei

**Comment by nigyta** [comment]
Hi, @laxeye
Thank you for the comment. Actually, it had a post-link.sh script in the past. But it was removed as per the reviewer of the Bioconda recipe.
