### ISSUE TITLE
Possible for faster speed?

### ISSUE THREAD

**Issue by Tonny-zhou** [nigyta/dfast_core#43]
Dear author,

Thanks for this great bacterial annotation tools! When examining the source data of dfast, I found the threads used for blastp is only 1,  Is there any reason for this？

Yours,
Tonny

**Comment by nigyta** [comment]
Thank you for your interest.
DFAST splits a query FASTA file into smaller pieces and then invoke multiple BLASTP processes concurrently with 1 cpu per process. In most cases, this is faster than using multiple CPUs for 1 BLASTP process, although it may less efficient in terms of memory usage.

nigyta

**Comment by Tonny-zhou** [comment]
> Thank you for your interest. DFAST splits a query FASTA file into smaller pieces and then invoke multiple BLASTP processes concurrently with 1 cpu per process. In most cases, this is faster than using multiple CPUs for 1 BLASTP process, although it may less efficient in terms of memory usage.
> 
> nigyta

I'm sorry to bother you again...  By viewing the source code, i noticed the process of orthosearch does not split the query FASTA file and reference FASTA file, and i found this is the most time-consuming process  when i annotated a bacterial genome with pre-annotated reference file given to the parameter --references. Is anything could i do to shorten the annotation time?
