### ISSUE TITLE
Reference file does not exist

### ISSUE THREAD

**Issue by ryobon-dev** [nigyta/dfast_core#46]
I had installed dfast via conda.
The prgram aborted after GHOSTX initialized. I have attached the log file for your understanding about the issue.

COuld you tell me how to resolve this issue ?

[application.log.txt](https://github.com/nigyta/dfast_core/files/13659415/application.log.txt)

**Comment by nigyta** [comment]
After installing DFAST from Bioconda, you need to download the reference data as below.
```
dfast_file_downloader.py --protein dfast --cdd Cog --hmm TIGR
```
Please refer to the [instruction](Installation via conda).

**Comment by ryobon-dev** [comment]
Thanks,

 

Very sorry for this careless question.

 

Everything is  fine for DFAST.
