### ISSUE TITLE
Failed to create output directory

### ISSUE THREAD

**Issue by joao1980** [nigyta/dfast_core#49]
Thanks for the tool. However, I am getting the rror below.
Failed to create an output directory '/data/ouput/OUT'. Aborting...

Any idea on the issue?
Best regards,
Joao

**Comment by nigyta** [comment]
Could you clarify how you invoked DFAST?
Perhaps, you don't have permission to write /data.

**Comment by joao1980** [comment]
Hi,
Thanks for the reply. I managed to make it work. I was installing the tool inside a singularity container and had some bash script to automate the creation of the output folder. However, the permissions to write hadn't not been set. Now it is working.
Thanks for the help.
Cheers!
