### ISSUE TITLE
BLAST Database error: Error: Not a valid version 4 database.

### ISSUE THREAD

**Issue by yoheyokubo** [nigyta/dfast_core#55]
Thanks for developing the annotation tool. I have a question about the error when running the CDD search:
```
2024/10/10 13:07:18 RPSblast will be performed using 8 CPUs.
2024/10/10 13:07:18 Process aborted due to an error in CDDsearch.
2024/10/10 13:07:18 Process aborted due to an error in CDDsearch.
2024/10/10 13:07:18 Process aborted due to an error in CDDsearch.
2024/10/10 13:07:18 BLAST Database error: Error: Not a valid version 4 database.
```
I think this error occurred due to an incompatibility between RBSblast and the database used by RBSblast. How could I fix this error? After I git-cloned the repository to my local environment (instead of conda) and downloaded relevant databases following [the instruction](https://github.com/nigyta/dfast_core?tab=readme-ov-file#reference-databases), I erased _blastp, blastn, makeblast,_ and  _makeblastdb_ in the directory _dfast_core/bin/Linux_ because my environment has blast+ 2.15.0 as default. But that couldn't help.
I think these are related information (my local environment is masked by **).
```
2024/10/10 13:06:38 Running on Python 3.12.0 (main, Apr  4 2024, 11:38:01) [GCC 13.2.0].
...
2024/10/10 13:06:38 OS type is Linux.
...
2024/10/10 13:06:40 Checking Blastp version... 
2024/10/10 13:06:41 Blastp initialized. (Version 2.15.0)
...
2024/10/10 13:06:41 CDDsearch initialized.
2024/10/10 13:06:42 Setting CDDsearch options. {'skipAnnotatedFeatures': False, 'evalue_cutoff': 1e-06, 'database': '/home/**/dfast_core/db/cdd/Cog', 'rpsbproc_data': '/home/**/dfast_core/bin/common/rpsbproc_data'}
2024/10/10 13:06:42 Checking RPSblast version... 
2024/10/10 13:06:42 RPSblast initialized. (Version 2.6.0)
2024/10/10 13:06:42 Setting RPSblast options. {'skipAnnotatedFeatures': False, 'evalue_cutoff': 1e-06, 'database': '/home/**/dfast_core/db/cdd/Cog', 'rpsbproc_data': '/home/**/dfast_core/bin/common/rpsbproc_data'}
2024/10/10 13:06:42 Checking rpsbproc version... 
2024/10/10 13:06:42 rpsbproc initialized. (Version 0.11)
2024/10/10 13:06:42 Setting rpsbproc options. {'skipAnnotatedFeatures': False, 'evalue_cutoff': 1e-06, 'database': '/home/**/dfast_core/db/cdd/Cog', 'rpsbproc_data': '/home/**/dfast_core/bin/common/rpsbproc_data'}
```
I appreciate any help you can provide. 4日間くらい同じエラーに悩まされております。お忙しいところ恐縮ですが、どうぞよろしくお願いいたします。ご回答は日本語でも大丈夫です。

**Comment by nigyta** [comment]
Thank you for the feedback.

The `rpsblast` binary bundled in the software distribution does not support the current v4 Blast database.
DFAST uses Cog reference database available at [NCBI FTP server](https://ftp.ncbi.nlm.nih.gov//pub/mmdb/cdd/little_endian/). But it seems that the files have been updated recently, and they are no longer compatible with DFAST.

I would like to fix this in the future version, but for now, you can avoid the error by retrieving the older reference data following the procedure below.

```
cd db/cdd 
rm Cog.*  # delete existing files
wget https://ddbj.nig.ac.jp/public/software/dfast/cog.tar.gz
tar xf cog.tar.gz
```

(Japanese translation)
[NCBI FTP server](https://ftp.ncbi.nlm.nih.gov//pub/mmdb/cdd/little_endian/) で公開されている参照データ形式がv4に更新され、古いバージョンのrpsblastで動かなくなっているのがエラーの原因です。
将来、v4に対応できるようにする予定ですが、差しあたり、上記手順で古いバージョンの参照データに差し替えることで動くと思われます

**Comment by yoheyokubo** [comment]
Thank you so much for the quick response. The workaround worked perfectly! I appreciate your time and support.
